# Generated by Django 3.2.9 on 2021-12-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='body',
        ),
    ]
