# Generated by Django 3.2.9 on 2021-12-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='puid',
            field=models.CharField(max_length=100),
        ),
    ]
