# Generated by Django 3.2.9 on 2021-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0002_alter_article_puid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='puid',
            field=models.CharField(max_length=10000),
        ),
    ]
